var facts =[
"60 billion square meters of textiles are left on the cutting room floor anually",
"In Hong Kong, residents throw away the equivalent of 1,400 t-shirts every minute",
"'Buy less, choose well, make it last.'",
"It takes 2,700 litres of water to make just one t-shirt – that’s the amount of water an average person drinks over the course of 900 days",
"Fashion is the 2nd most polluting industry in the world, first one being oil",
"cotton is responsible for 2.6% of the global water use",
"polyester emits almost three times more carbon dioxide in its lifecycle than cotton",
"polyester is present in 60% of today's clothing and it takes decades to degrade",
"as much as 95% of clothes thrown out can be re-worn, reused or recycled",
"in the US, the textile industry is the 5th largest contributor to the nation's overall co2 emissions",
"60 billion kilos of fabric are produced annually",
"textiles account for 19.8 tons of the average American’s annual greenhouse emissions",
"growing cotton accounts for 22.5% of global insecticide use",
"Estimates suggest that consumers treat the lowest priced garments as disposable, discarding them after seven or eight wears",
"Each year over 80 billion pieces of clothing are produced worldwide - three out of four garments end up in landfills",
"Syrian refugee children are making clothing for Marks & Spencer and ASOS in Turkish sweatshops",
"In developing countries, an estimated 168 million children ages 5 to 14 are forced to work",
"Beyoncé‘s clothing range with Topshop, is made by workers paid less than 44p an hour in ‘sweatshop’ conditions",
"in bangladesh there are no collective rights, no trade union rights and no pension",
"H&M is the second largest corporation in clothing history, with annual revenues of more than $18 billion",
"in Cambodia, following a garment workers strike, 5 died, 23 were arrested and 40 injured",
"big companies don’t own the factories where their clothes are produced and therefore are not accountable for the condition of the workers",
"the customer is in charge. if you don’t like it, don’t buy into it.",
"'this cost at what cost?'",
"garment workers put blood and sweat into clothes we wear 1.7 times before throwing them away",
"in kanpur, everyday more than 50 million litres of toxic wastewater is poured out of the local tanneries",
"the average american throws away 82 pounds of textile waste each year",
"only 10% of the clothes that are donated to charity actually gets sold in local thrift stores",
"11 billion tons of textile waste is thrown away from the US alone each year. Most of it is non bio-degradable",
"20 years ago we used to buy 400% less clothes than today",
"in the last 16 years there have been more than 250’000 recorded cotton farmer suicides in india. that’s the biggest wave of suicide in history.",
"punjab is the largest user of pesticide in india.  The state produces nearly 70% of the best quality cotton of the country.",
"the more you use pesticides, the more you need to use them. they’re called 'ecological narcotics'",
"1 in 6 people alive in the world today work in some part of the global fashion industry",
"fashion is the most labor dependent industry on earth",
];

